# -*- coding: utf-8 -*-
"""Customer Behavioural Segmentation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16RFo7J7_9FahD4oVKwswqmJY7-IGChPk
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score, davies_bouldin_score

import scipy.cluster.hierarchy as sch

!pip install umap-learn
import umap

from google.colab import files
uploaded = files.upload()

import zipfile

# Unzip mall customers dataset
with zipfile.ZipFile("archive.zip", 'r') as zip_ref:
    zip_ref.extractall("mall_data")

# Unzip online retail dataset
with zipfile.ZipFile("online+retail+ii.zip", 'r') as zip_ref:
    zip_ref.extractall("retail_data")

import os

print("Mall folder:", os.listdir("mall_data"))
print("Retail folder:", os.listdir("retail_data"))

import pandas as pd

mall_df = pd.read_csv("mall_data/Mall_Customers.csv")
retail_df = pd.read_excel("retail_data/online_retail_II.xlsx")

# If it's split into 2 parts:
# retail_1 = pd.read_excel("online_retail_II_2010-2011.xlsx")
# retail_2 = pd.read_excel("online_retail_II_2009-2010.xlsx")
# retail_df = pd.concat([retail_1, retail_2])

mall_df = mall_df.rename(columns={
    "Genre": "Gender",
    "Annual Income (k$)": "AnnualIncome",
    "Spending Score (1-100)": "SpendingScore"
})
mall_df.head()

from sklearn.preprocessing import StandardScaler, LabelEncoder

df_m = mall_df.copy()

# Encode Gender
le = LabelEncoder()
df_m["GenderEncoded"] = le.fit_transform(df_m["Gender"])

features = ["Age", "AnnualIncome", "SpendingScore", "GenderEncoded"]

X_mall = df_m[features].copy()

# Scaling
scaler = StandardScaler()
X_mall_scaled = scaler.fit_transform(X_mall)

from sklearn.decomposition import PCA

pca = PCA(n_components=2, random_state=42)
X_mall_pca = pca.fit_transform(X_mall_scaled)

reducer = umap.UMAP(n_components=2, n_neighbors=15, min_dist=0.1, random_state=42)
X_mall_umap = reducer.fit_transform(X_mall_scaled)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(7,5))
plt.scatter(X_mall_umap[:, 0], X_mall_umap[:, 1], alpha=0.6)
plt.title("Mall Data - Raw UMAP Projection")
plt.show()

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

scores = {}
for k in range(2, 11):
    labels = KMeans(n_clusters=k, n_init=10, random_state=42).fit_predict(X_mall_scaled)
    scores[k] = silhouette_score(X_mall_scaled, labels)

scores

optimal_k = max(scores, key=scores.get)
optimal_k

kmeans = KMeans(n_clusters=optimal_k, n_init=10, random_state=42)
mall_labels = kmeans.fit_predict(X_mall_scaled)

df_m["Cluster"] = mall_labels

plt.figure(figsize=(7,5))
sns.scatterplot(x=X_mall_umap[:,0], y=X_mall_umap[:,1],
                hue=df_m["Cluster"], palette="tab10")
plt.title("Mall Dataset - KMeans Clusters on UMAP")
plt.show()

cluster_profile = df_m.groupby("Cluster")[["Age", "AnnualIncome", "SpendingScore"]].mean()
cluster_profile

persona_map = {
    0: "Young Luxury Shopper",
    1: "High Income Low Spending",
    2: "Budget Conscious",
    3: "Average Income Average Spend",
    4: "Young High Spenders",
    5: "Older High Spenders",
    6: "Loyal Moderate Spenders",
    7: "High Income Very High Spend",
    8: "Low Income Low Spend",
    9: "Older Low Spending"
}

df_m["Persona"] = df_m["Cluster"].map(persona_map)
df_m.head()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,5))
sns.countplot(data=df_m, x="Persona", order=df_m["Persona"].value_counts().index)
plt.xticks(rotation=45, ha="right")
plt.title("Number of Customers per Persona")
plt.tight_layout()
plt.show()

persona_stats = df_m.groupby("Persona")[["Age","AnnualIncome","SpendingScore"]].mean()
persona_stats

persona_stats.plot(kind="bar", figsize=(10,6))
plt.title("Average Age / Income / Spending by Persona")
plt.xticks(rotation=45, ha="right")
plt.ylabel("Mean Value")
plt.tight_layout()
plt.show()

reducer = umap.UMAP(
    n_components=2,
    n_neighbors=15,
    min_dist=0.1,
    random_state=42
)

X_mall_umap = reducer.fit_transform(X_mall_scaled)

plt.figure(figsize=(7,6))
sns.scatterplot(
    x=X_mall_umap[:,0],
    y=X_mall_umap[:,1],
    hue=df_m["Persona"],
    palette="tab10"
)
plt.title("Mall Customers – Personas in UMAP Space")
plt.legend(title="Persona", bbox_to_anchor=(1.05,1), loc="upper left")
plt.tight_layout()
plt.show()

from sklearn.metrics import silhouette_score, davies_bouldin_score

sil = silhouette_score(X_mall_scaled, df_m["Cluster"])
db  = davies_bouldin_score(X_mall_scaled, df_m["Cluster"])

print("Silhouette Score:", sil)
print("Davies-Bouldin Score:", db)

df_m.to_csv("mall_customer_segments.csv", index=False)

from google.colab import files
files.download("mall_customer_segments.csv")

import zipfile, os

with zipfile.ZipFile("online+retail+ii.zip", "r") as z:
    z.extractall("retail_data")

os.listdir("retail_data")

import pandas as pd

retail_df = pd.read_excel("retail_data/online_retail_II.xlsx")
retail_df.head()

retail_df = retail_df[~retail_df["Invoice"].astype(str).str.startswith("C")]

# Drop rows without customer id
retail_df = retail_df.dropna(subset=["Customer ID"])

# Total amount
retail_df["TotalAmount"] = retail_df["Price"] * retail_df["Quantity"]

NOW = retail_df["InvoiceDate"].max() + pd.Timedelta(days=1)

rfm = retail_df.groupby("Customer ID").agg({
    "InvoiceDate": lambda x: (NOW - x.max()).days,
    "Invoice": "count",
    "TotalAmount": "sum"
}).reset_index()

rfm.columns = ["CustomerID", "Recency", "Frequency", "Monetary"]
rfm.head()

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

scaler = StandardScaler()
X_rfm_scaled = scaler.fit_transform(rfm[["Recency","Frequency","Monetary"]])

k_rfm = 10

kmeans_rfm = KMeans(n_clusters=k_rfm, n_init=10, random_state=42)
rfm["Cluster"] = kmeans_rfm.fit_predict(X_rfm_scaled)

reducer_rfm = umap.UMAP(n_components=2, random_state=42)
X_rfm_umap = reducer_rfm.fit_transform(X_rfm_scaled)

plt.figure(figsize=(7,6))
sns.scatterplot(
    x=X_rfm_umap[:,0],
    y=X_rfm_umap[:,1],
    hue=rfm["Cluster"],
    palette="tab10"
)
plt.title("Online Retail II – RFM Clusters (UMAP)")
plt.tight_layout()
plt.show()

rfm_profile = rfm.groupby("Cluster")[["Recency","Frequency","Monetary"]].mean()
rfm_profile

persona_map_retail = {
    6: "Champion / VIP Royal Customers",
    5: "Premium VIP Spenders",
    1: "Loyal High Spenders",
    4: "Recent Active Buyers",
    7: "Growing Loyalists",
    9: "Potential Loyalists",
    2: "Regular Budget Buyers",
    0: "Churn Risk Customers",
    8: "Low Value Customers",
    3: "Lost Customers"
}

rfm["Persona"] = rfm["Cluster"].map(persona_map_retail)
rfm.head()

plt.figure(figsize=(9,7))
sns.scatterplot(
    x=X_rfm_umap[:,0],
    y=X_rfm_umap[:,1],
    hue=rfm["Persona"],
    palette="tab10"
)
plt.title("Online Retail Personas via UMAP")
plt.legend(title="Persona", bbox_to_anchor=(1.05,1))
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,5))
sns.countplot(
    data=rfm,
    x="Persona",
    order=rfm["Persona"].value_counts().index
)
plt.xticks(rotation=45, ha="right")
plt.title("Customer Persona Distribution")
plt.tight_layout()
plt.show()

from sklearn.metrics import silhouette_score, davies_bouldin_score

print("Silhouette Score:", silhouette_score(X_rfm_scaled, rfm["Cluster"]))
print("Davies-Bouldin Score:", davies_bouldin_score(X_rfm_scaled, rfm["Cluster"]))

rfm.to_csv("online_retail_customer_segments.csv", index=False)

from google.colab import files
files.download("online_retail_customer_segments.csv")

# Attach UMAP coordinates to dataframes
df_m["UMAP1"] = X_mall_umap[:, 0]
df_m["UMAP2"] = X_mall_umap[:, 1]

rfm["UMAP1"] = X_rfm_umap[:, 0]
rfm["UMAP2"] = X_rfm_umap[:, 1]

!pip install gradio -q

import gradio as gr
import matplotlib.pyplot as plt
import seaborn as sns

def mall_lookup(customer_id):
    try:
        customer_id = int(customer_id)
    except:
        return "Please enter a valid integer CustomerID", None

    row = df_m[df_m["CustomerID"] == customer_id]

    if row.empty:
        return f"No customer found with ID {customer_id}", None

    persona = row["Persona"].iloc[0]
    short_df = row[["CustomerID", "Gender", "Age", "AnnualIncome",
                    "SpendingScore", "Cluster", "Persona"]]
    return f"Persona: {persona}", short_df

def retail_lookup(customer_id):
    try:
        customer_id = float(customer_id)
    except:
        return "Please enter a valid numeric CustomerID", None

    row = rfm[rfm["CustomerID"] == customer_id]

    if row.empty:
        return f"No customer found with ID {customer_id}", None

    persona = row["Persona"].iloc[0]
    short_df = row[["CustomerID", "Recency", "Frequency",
                    "Monetary", "Cluster", "Persona"]]
    return f"Persona: {persona}", short_df

def plot_umap(dataset):
    fig, ax = plt.subplots(figsize=(7, 6))

    if dataset == "Mall Customers":
        sns.scatterplot(
            data=df_m,
            x="UMAP1", y="UMAP2",
            hue="Persona",
            palette="tab10",
            ax=ax,
            s=20
        )
        ax.set_title("Mall Customers – UMAP by Persona")
    else:
        sns.scatterplot(
            data=rfm,
            x="UMAP1", y="UMAP2",
            hue="Persona",
            palette="tab10",
            ax=ax,
            s=20
        )
        ax.set_title("Online Retail – UMAP by Persona")

    ax.legend(title="Persona", bbox_to_anchor=(1.05, 1), loc="upper left")
    fig.tight_layout()
    return fig

with gr.Blocks() as demo:
    gr.Markdown("## 🛍️ Customer Segmentation Dashboard (Mall + Online Retail)")

    with gr.Tab("Mall Customers"):
        gr.Markdown("### Look up a mall customer and view their persona")

        mall_id_in = gr.Number(label="CustomerID", value=1, precision=0)
        mall_info_out = gr.Textbox(label="Persona & Message")
        mall_df_out = gr.Dataframe(label="Customer Details", interactive=False)

        mall_btn = gr.Button("Lookup Customer")
        mall_btn.click(
            mall_lookup,
            inputs=mall_id_in,
            outputs=[mall_info_out, mall_df_out]
        )

        gr.Markdown("### UMAP visualization of mall personas")
        mall_plot_btn = gr.Button("Show UMAP")
        mall_plot_out = gr.Plot()
        mall_plot_btn.click(
            lambda: plot_umap("Mall Customers"),
            inputs=None,
            outputs=mall_plot_out
        )

    with gr.Tab("Online Retail II"):
        gr.Markdown("### Look up a retail customer and view their persona")

        retail_id_in = gr.Number(label="CustomerID", value=12347)
        retail_info_out = gr.Textbox(label="Persona & Message")
        retail_df_out = gr.Dataframe(label="Customer RFM & Segment", interactive=False)

        retail_btn = gr.Button("Lookup Customer")
        retail_btn.click(
            retail_lookup,
            inputs=retail_id_in,
            outputs=[retail_info_out, retail_df_out]
        )

        gr.Markdown("### UMAP visualization of retail personas")
        retail_plot_btn = gr.Button("Show UMAP")
        retail_plot_out = gr.Plot()
        retail_plot_btn.click(
            lambda: plot_umap("Online Retail II"),
            inputs=None,
            outputs=retail_plot_out
        )

demo.launch(share=True)